#!/bin/sh

if test -z "$1"; then
    echo "CRITICAL: missing dependency to check" >&2
    exit 1
fi

if test -z "$TMPDIR"; then
    TMPDIR=/tmp
fi
TMPFILE=$TMPDIR/$1.$$

if test "$2"; then
    TARGET="$1/$2"
else
    TARGET=$1
fi

if ! wget https://snyk.io/test/npm/$TARGET -q -O $TMPFILE; then
    echo "CRITICAL: failed fetching $TARGET data from snyk.io" >&2
    exit 2
elif ! test -s $TMPFILE; then
    echo "CRITICAL: null-sized file fetching $TARGET data from snyk.io" >&2
    rm -f $TMPFILE
    exit 2
fi

if ! grep '<meta name="description" content="No vulnerabilities found. This is a good thing!">' $TMPFILE >/dev/null; then
    parseRemediation $TMPFILE | sed -e 's|<p>||g' -e 's|</p>||g' -e 's|<code>||g' -e 's|</code>||g' -e 's|^[ \t]*||' -e 's|\.$||'
fi

rm -f $TMPFILE

exit 0
