#!/bin/sh

if test -z "$1"; then
    echo "CRITICAL: missing dependency to check" >&2
    exit 1
fi

if test -z "$TMPDIR"; then
    TMPDIR=/tmp
fi
TMPFILE=$TMPDIR/$1.$$

if test "$NPMJS_THROTTLE"; then
    if test "$NPMJS_THROTTLE" -ge 0 >/dev/null 2>&1; then
	case "$NPMJS_THROTTLE" in
	    0-10)		;;
	    11-50)	sleep 1 ;;
	    51-300)	sleep 2	;;
	    301-600)	sleep 3	;;
	    601-999)	sleep 4	;;
	    *)		sleep 5	;;
	esac
    fi
fi
if ! curl -H 'Cache-Control: no-cache' https://www.npmjs.com/package/$1 >$TMPFILE 2>/dev/null; then
    echo "CRITICAL: failed fetching $1 data from npmjs.com" >&2
    rm -f $TMPFILE
    exit 2
elif ! test -s $TMPFILE; then
    echo "CRITICAL: null-sized file fetching $1 data from npmjs.com" >&2
    rm -f $TMPFILE
    exit 2
elif ! grep '"distTags":{"latest":"' $TMPFILE >/dev/null; then
    echo "CRITICAL: failed matching last version for $1 on npmjs.com" >&2
    rm -f $TMPFILE
    exit 3
fi

VERS=`grep '"distTags":{"latest":"' $TMPFILE | sed 's|.*"latest":"\([^"]*\)".*|\1|'`
rm -f $TMPFILE

if test -z "$VERS"; then
    echo "CRITICAL: failed extracting last known version of $1 from npmjs.com" >&2
    exit 4
fi

echo $VERS

exit 0
