#!/bin/sh

if test -z "$1"; then
    echo "CRITICAL: missing dependency to check" >&2
    exit 1
fi

if test -z "$TMPDIR"; then
    TMPDIR=/tmp
fi
TMPFILE=$TMPDIR/$1.$$

if test "$2"; then
    TARGET="$1/$2"
else
    TARGET=$1
fi

if test "$SNYK_THROTTLE"; then
    if test "$SNYK_THROTTLE" -ge 0 >/dev/null 2>&1; then
	case "$SNYK_THROTTLE" in
	    0-10)		;;
	    11-50)	sleep 1 ;;
	    51-300)	sleep 2	;;
	    301-600)	sleep 3	;;
	    601-999)	sleep 4	;;
	    *)		sleep 5	;;
	esac
    fi
fi
if ! curl -H 'Cache-Control: no-cache' https://snyk.io/test/npm/$TARGET >$TMPFILE 2>/dev/null; then
    echo "CRITICAL: failed fetching $TARGET data from snyk.io" >&2
    exit 2
elif ! test -s $TMPFILE; then
    echo "CRITICAL: null-sized file fetching $TARGET data from snyk.io" >&2
    rm -f $TMPFILE
    exit 2
fi

if ! grep '<meta name="description" content="No vulnerabilities found. This is a good thing!">' $TMPFILE >/dev/null; then
    parseRemediation $TMPFILE | sed -e 's|<[/]*p>||g' -e 's|<a href=[^>]*>||g' -e 's|</a>||g' -e 's|<[/]*code>||g' -e 's|<[/]*strong>||g' -e 's|&gt[; ]|>|g' -e 's|&lt[; ]|<|g' -e 's|^[ \t]*||' -e 's|\.$||'
fi

rm -f $TMPFILE

exit 0
