#!/bin/sh

if test -z "$1"; then
    echo "CRITICAL: missing repository argument" >&2
    exit 1
elif test -z "$WORKDIR"; then
    echo "CRITICAL: WORKDIR not set, can not proceed" >&2
    exit 1
elif ! test -d $WORKDIR/$1/.git; then
    echo "CRITICAL: repository $1 does not exist in $WORKDIR" >&2
    exit 1
elif ! test -s $WORKDIR/$1/package.json; then
    echo "CRITICAL: repository $1 has no package.json" >&2
    exit 1
fi

cat $WORKDIR/$1/package.json | parseJson | sed 's|^"\([^"]*\)": "\([^"]*\)".*|\1 \2|'

exit $?
