#!/bin/sh

if test -z "$LOGDIR"; then
    LOGDIR=./logs
fi
if ! test -d $LOGDIR; then
    echo "CRITICAL: cannot find logs directory" >&2
    exit 1
fi

find $LOGDIR -maxdepth 1 -type f -mtime 1 -user `id -u` \( -name '*npminstall.log' -o -name '*shrinkwrap.log' -o -name '*shrinkpack.log' \) -exec rm -f {} \;

exit 0
