#!/bin/sh

if test -z "$WORKDIR"; then
    echo "CRITICAL: WORKDIR not set, can not proceed" >&2
    exit 1
elif test -z "$DBDIR"; then
    DBDIR=$WORKDIR
fi

if ! test -d $WORKDIR; then
    echo "CRITICAL: repository working directory does not exist" >&2
    exit 1
elif ! test -d $DBDIR; then
    echo "CRITICAL: database directory does not exist" >&2
    exit 1
elif ! test -e "$DBDIR/exclude-from-updates"; then
    echo "WARNING: exclude-from-updates absent, creating empty dataset" >&2
    touch "$DBDIR/exclude-from-updates"
fi

if test "$1"; then
    TARGET=$1
    QUICK=true
else
    QUICK=false
fi

while :
do
    if test "$TARGET" = q -o "$TARGET" = quit; then
	exit 0
    elif echo "$TARGET" | grep / >/dev/null; then
	echo "<add$ WARNING: malformatted NodeJS module name $TARGET"
	if $QUICK; then
	    exit 2
	fi
    elif grep "^$TARGET$" $DBDIR/exclude-from-updates >/dev/null; then
	echo "<add$ WARNING: $TARGET already configured to be ignored"
	if $QUICK; then
	    exit 0
	fi
    elif echo "$TARGET" | grep '[a-zA-Z0-9]' >/dev/null; then
	echo "$TARGET" >>$DBDIR/exclude-from-updates
	echo "<add$ NOTICE: added $TARGET"
	if $QUICK; then
	    exit 0
	fi
    else
	echo "<add$ WARNING: malformatted NodeJS module name $TARGET"
    fi
    echo "<add$ type in a NodeJS name, or either q to quit"
    echo -n "add$> "
    read TARGET
done

exit 2
