#!/bin/sh

if test -z "$WORKDIR"; then
    echo "CRITICAL: WORKDIR not set, can not proceed" >&2
    exit 1
elif test -z "$DBDIR"; then
    DBDIR=$WORKDIR
fi

if ! test -d $WORKDIR; then
    echo "CRITICAL: repository working directory does not exist" >&2
    exit 1
elif ! test -d $DBDIR; then
    echo "CRITICAL: database directory does not exist" >&2
    exit 1
elif ! test -e "$DBDIR/exclude-from-updates"; then
    echo "CRITICAL: exclude-from-updates absent" >&2
    exit 1
fi

if test "$1"; then
    MATCH="$1"
else
    MATCH='.*'
fi

cat $DBDIR/exclude-from-updates | sort | grep -E "$MATCH"

exit $?
