#!/bin/sh

if test -z "$WORKDIR"; then
    echo "CRITICAL: WORKDIR not set, can not proceed" >&2
    exit 1
elif test -z "$DBDIR"; then
    DBDIR=$WORKDIR
fi

if ! test -d $WORKDIR; then
    echo "CRITICAL: repository working directory does not exist" >&2
    exit 1
elif ! test -d $DBDIR; then
    echo "CRITICAL: database directory does not exist" >&2
    exit 1
elif ! test -e "$DBDIR/exclude-from-updates"; then
    echo "CRITICAL: exclude-from-updates absent" >&2
    exit 1
fi

if test "$1"; then
    TARGET=$1
    QUICK=true
else
    QUICK=false
fi

while :
do
    if test "$TARGET" = q -o "$TARGET" = quit; then
	exit 0
    elif echo "$TARGET" | grep / >/dev/null; then
	echo "<del$ WARNING: malformatted NodeJS module name $TARGET"
	if $QUICK; then
	    exit 2
	fi
    elif grep "^$TARGET$" $DBDIR/exclude-from-updates >/dev/null; then
	if ! sed -i "/^$TARGET$/d" $DBDIR/exclude-from-updates; then
	    if grep "^$TARGET$" $DBDIR/exclude-from-updates >/dev/null; then
		echo "<del$ WARNING: failed removing $TARGET from ignored dependencies"
		if $QUICK; then
		    exit 2
		fi
	    else
		echo "<del$ NOTICE: removed $TARGET from ignored dependencies"
	    fi
	else
	    echo "<del$ NOTICE: removed $TARGET from ignored dependencies"
	fi
	if $QUICK; then
	    exit 0
	fi
    else
	echo "<del$ WARNING: malformatted NodeJS module name $TARGET"
	if $QUICK; then
	    exit 2
	fi
    fi
    echo "<del$ type in a NodeJS module name, or either q or quit to exit"
    echo -n "del$> "
    read TARGET
done

exit 2
