#!/bin/sh

if test -z "$WORKDIR"; then
    echo "CRITICAL: WORKDIR not set, can not proceed" >&2
    exit 1
elif test -z "$DBDIR"; then
    DBDIR=$WORKDIR
fi

if ! test -d $DBDIR; then
    echo "CRITICAL: database directory does not exist" >&2
    exit 1
elif ! test -e "$DBDIR/nodejs-update-db"; then
    echo "CRITICAL: nodejs-update-db absent" >&2
    exit 1
fi

if test "$1"; then
    MATCH="$1"
else
    MATCH='.*'
fi

sed 's|;| |g' $DBDIR/nodejs-update-db | while read url name lastCheck
    do
	if test "$lastCheck" = 0; then
	    lastCheckString="has not been checked yet"
	elif test "$lastCheck" -gt 0 >/dev/null; then
	    lastCheckString="last checked on `date -d @$lastCheck` ($lastCheck)"
	else
	    lastCheckString="illegal last check date on DB"
	fi
	echo "$name (from $url), $lastCheckString"
    done | sort | grep -E "$MATCH"

exit $?
