#!/bin/sh

if test -z "$WORKDIR"; then
    echo "CRITICAL: WORKDIR not set, can not proceed" >&2
    exit 1
elif test -z "$DBDIR"; then
    DBDIR=$WORKDIR
fi
#if test -z "$CACHETTL"; then
#   CACHETTL=3600
#fi

if ! test -d $WORKDIR; then
    echo "CRITICAL: repository working directory does not exist" >&2
    exit 1
elif ! test -d $DBDIR; then
    echo "CRITICAL: database directory does not exist" >&2
    exit 1
elif ! test -e "$DBDIR/npmjs-cache"; then
    echo "WARNING: npmjs-cache is absent" >&2
fi

if test "$1"; then
    TARGET=$1
#   TTL=$2
    QUICK=true
else
#   TTL=$CACHETTL
    QUICK=false
fi

while :
do
    if test "$TARGET"; then
#	if echo "$TARGET" | grep -E '^[ \t]*CACHETTL=[0-9]' >/dev/null; then
#	    TTL=`echo $TARGET | sed 's|.*CACHETTL=\([0-9]*\).*|\1|'`
#	    echo "<add$ NOTICE: changed TTL to $TTL"
	if echo "$TARGET"  | grep -E '^[^_\./][^/]*$' >/dev/null; then
	    if getVersionFromNpmjs $TARGET >/dev/null 2>&1; then
		version=`getVersionFromNpmjs $TARGET 2>/dev/null`
		if test "$version"; then
		    lastCheck=`date +%s`
		    if grep "^$TARGET;" $DBDIR/npmjs-cache >/dev/null 2>&1; then
			sed -i "s|^$TARGET;.*|$TARGET;$version;$lastCheck|" $DBDIR/npmjs-cache
			echo "<add$ NOTICE: updated $TARGET"
		    else
			echo "$TARGET;$version;$lastCheck" >>$DBDIR/npmjs-cache
			echo "<add$ NOTICE: added $TARGET"
		    fi
		else
		    echo "<add$ WARNING: failed extracting last version for $TARGET from npmjs.com" >&2
		    if $QUICK; then
			exit 2
		    fi
		fi
		if $QUICK; then
		    exit 0
		fi
	    else
		echo "<add$ CRITICAL: failed fetching $TARGET data from npmjs.com" >&2
		if $QUICK; then
		    exit 2
		fi
	    fi
	elif test "$TARGET" = _q -o "$TARGET" = _quit; then
	    exit 0
	else
	    echo "<add$ WARNING: malformatted NodeJS module name $TARGET"
	    if $QUICK; then
		exit 2
	    fi
	fi
    fi
    echo "<add$ type in a NodeJS name, or either _q to _quit"
    echo -n "add$> "
    read TARGET
done

exit 2
