#!/usr/bin/awk -f

BEGIN {
    isdep = 0
} {
    if (isdep == 1) {
	if ($1 == "}," || $1 == "}") {
	    isdep = 0
	} else {
	    print $1" "$2;
	}
    }
    if ($1 ~ /[Dd]ependencies/) {
	isdep = 1;
    }
}
