#!/usr/bin/env python

import sys, json;

if len(sys.argv) < 2:
    sys.stderr.write("missing argument\n");
    sys.exit(1);

ary = json.load(sys.stdin);

for item in ary:
    if item["vcs_revision"] == sys.argv[1]:
	print item["status"];
