#!/usr/bin/awk -f

BEGIN {
    isremediation = 0
} {
    if ($0 ~ /<h2 .*Remediation/) {
	isremediation = 1;
    } else {
	if ($0 ~ /<h2 /) {
	    isremediation = 0
	}
	if (isremediation == 1) {
	    print $0
	}
    }
}
